import type { Metadata } from "next";
import { Poppins, M_PLUS_Code_Latin } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

const mPlusCodeLatin = M_PLUS_Code_Latin({
  variable: "--font-m-plus-code-latin",
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', ]
});

export const metadata: Metadata = {
  title: "Mohamed Sanjeed Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${mPlusCodeLatin.className}`}>
        <Navbar />
        <Toaster />
        {children}
        <Footer />
      </body>
    </html>
  );
}
